{% set name = "numberpartitioning" %}
{% set version = "0.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/numberpartitioning-{{ version }}.tar.gz
  sha256: 69f91be64a9c9e303f1ab681c2e065ac1b72926f382f3abcf916d205db6db5d2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - numberpartitioning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fuglede/numberpartitioning
  summary: Pure Python solver for the multi-way partition problem
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fuglede
